// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBauV5pz-XS6jkiK9ISTwoRqkkvqQtqssw',
    appId: '1:850471152876:web:6b02a6ba5eae2875d749c9',
    messagingSenderId: '850471152876',
    projectId: 'gente-fera-fc-2',
    authDomain: 'gente-fera-fc-2.firebaseapp.com',
    storageBucket: 'gente-fera-fc-2.firebasestorage.app',
    measurementId: 'G-KGHQK3TY4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2VgA22wbkm6PqVKaA5fn1HqAr1EgAW2A',
    appId: '1:850471152876:android:e3bc6f4f18631210d749c9',
    messagingSenderId: '850471152876',
    projectId: 'gente-fera-fc-2',
    storageBucket: 'gente-fera-fc-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAcRrnNpsgOekgYLEizG_zAq5P6EzzTZo',
    appId: '1:850471152876:ios:cb344c56ad601ed9d749c9',
    messagingSenderId: '850471152876',
    projectId: 'gente-fera-fc-2',
    storageBucket: 'gente-fera-fc-2.firebasestorage.app',
    iosBundleId: 'com.example.appFutebol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAcRrnNpsgOekgYLEizG_zAq5P6EzzTZo',
    appId: '1:850471152876:ios:cb344c56ad601ed9d749c9',
    messagingSenderId: '850471152876',
    projectId: 'gente-fera-fc-2',
    storageBucket: 'gente-fera-fc-2.firebasestorage.app',
    iosBundleId: 'com.example.appFutebol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBauV5pz-XS6jkiK9ISTwoRqkkvqQtqssw',
    appId: '1:850471152876:web:3eddfdadf8534eaed749c9',
    messagingSenderId: '850471152876',
    projectId: 'gente-fera-fc-2',
    authDomain: 'gente-fera-fc-2.firebaseapp.com',
    storageBucket: 'gente-fera-fc-2.firebasestorage.app',
    measurementId: 'G-CF4YJXF63K',
  );

}